### ISSUE TITLE
报一个小bug

### ISSUE THREAD

**Issue by anosorae** [Fenghuapiao/PyQuickInstall#13]
首先，感谢作者制作了这个小工具，很好用👍
在一般情况下这个工具都挺好用，但是在root用户执行 `pqi ls` 的时候会由于`/root/`目录下没有 `.config`文件夹而报错。
```bash
Traceback (most recent call last):
  File "/root/miniconda3/envs/mf1.1_ms2.3_py39/bin/pqi", line 5, in <module>
    from PQI.pqi import main
  File "/root/miniconda3/envs/mf1.1_ms2.3_py39/lib/python3.9/site-packages/PQI/pqi.py", line 42, in <module>
    os.mkdir(dir_path)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/pip'
```
我对此的解决办法都是手动`mkdir .config`。
但是还是希望作者能够修复一下这个bug，感谢🙏

**Comment by Frankr0** [comment]
WSL2 Ubuntu python3.10非root用户安装也出现了相同报错

```
Traceback (most recent call last):
  File "/home/orkk/miniforge3/bin/pqi", line 5, in <module>
    from PQI.pqi import main
  File "/home/orkk/miniforge3/lib/python3.10/site-packages/PQI/pqi.py", line 42, in <module>
    os.mkdir(dir_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/orkk/.config/pip'
```

**Comment by yhangf** [comment]
已经合并@anosorae 提交的修复代码，感谢！
